time_before_break: 20 #minutes
shell_safety_duration: 5 #seconds

editor: "vscode"
terminal: "kitty"
browser: "Mozilla Firefox"

#list of all keys
# ['\t', '\n', '\r', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', 'accept', 'add', 'alt', 'altleft', 'altright', 'apps', 'backspace', 'browserback', 'browserfavorites', 'browserforward', 'browserhome', 'browserrefresh', 'browsersearch', 'browserstop', 'capslock', 'clear', 'convert', 'ctrl', 'ctrlleft', 'ctrlright', 'decimal', 'del', 'delete', 'divide', 'down', 'end', 'enter', 'esc', 'escape', 'execute', 'f1', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f2', 'f20', 'f21', 'f22', 'f23', 'f24', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'final', 'fn', 'hanguel', 'hangul', 'hanja', 'help', 'home', 'insert', 'junja', 'kana', 'kanji', 'launchapp1', 'launchapp2', 'launchmail', 'launchmediaselect', 'left', 'modechange', 'multiply', 'nexttrack', 'nonconvert', 'num0', 'num1', 'num2', 'num3', 'num4', 'num5', 'num6', 'num7', 'num8', 'num9', 'numlock', 'pagedown', 'pageup', 'pause', 'pgdn', 'pgup', 'playpause', 'prevtrack', 'print', 'printscreen', 'prntscrn', 'prtsc', 'prtscr', 'return', 'right', 'scrolllock', 'select', 'separator', 'shift', 'shiftleft', 'shiftright', 'sleep', 'space', 'stop', 'subtract', 'tab', 'up', 'volumedown', 'volumemute', 'volumeup', 'win', 'winleft', 'winright', 'yen', 'command', 'option', 'optionleft', 'optionright']
Mozilla Firefox:
- go foward: "alt right"
- go back: "alt left"
- next tab: "ctrl \t"
- private tab: "ctrl shift p"
- new bookmark: "ctrl d"
- search bar: "ctrl j"

Visual Studio Code:
- new command: "ctrl shift p"


model:
- default: nvidia_nemo
-
  nvidia_nemo:
    - model_path: "nvidia/stt_en_conformer_ctc_medium.nemo"
    - pretrained_name: "stt_en_conformer_ctc_medium"
    - cuda : -1
    - audio_dir : "Assets/"
    - audio_type : "wav"
    - batch_size : 128

alphabet: 
  - air       : "a" 
  - bat       : "b" 
  - cap       : "c" 
  - drum      : "d" 
  - each      : "e" 
  - fine      : "f" 
  - gust      : "g" 
  - harp      : "h" 
  - sit       : "i" 
  - jury      : "j" 
  - crunch    : "k" 
  - look      : "l" 
  - made      : "m" 
  - near      : "n" 
  - odd       : "o" 
  - pit       : "p" 
  - quench    : "q" 
  - red       : "r" 
  - sun       : "s" 
  - trap      : "t" 
  - urge      : "u" 
  - vest      : "v" 
  - whale     : "w" 
  - plex      : "x" 
  - yank      : "y" 
  - zip       : "z"    