Timer:
# in minutes
 - time_before_break: 20 

Model:
- default: nvidia_nemo
-
  nvidia_nemo:
    - model_path: "nvidia/stt_en_conformer_ctc_medium.nemo"
    - pretrained_name: "stt_en_conformer_ctc_medium"
    - cuda : -1
    - audio_dir : "Assets/"
    - audio_type : "wav"
    - batch_size : 128
