[book]
authors = ["https://github.com/C-Loftus"]
language = "en"
multilingual = false
src = "src"
title = "Starling Documentation"

[output.html]
git-repository-url = "https://github.com/C-Loftus/Starling"
git-repository-icon = "fa-github"
default-theme="rust"
preferred-dark-theme = "rust"

preferred-light-theme = "rust"